version: '3.8'

services:
  api:
    container_name: ${APP_NAME:-sar_api}
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./config:/app/config
    depends_on:
      - mongodb
    networks:
      - sar_network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sar_network

networks:
  sar_network:
    driver: bridge

volumes:
  mongodb_data: